---
title: "scratch"
author: "Derek Sollberger"
date: '2022-05-30'
output: html_document
---

```{r}
library("corrplot")
library("forcats")
library("janitor")
library("skimr")
library("tidyverse")
```

```{r}
# https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-05-31
reputation <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-31/reputation.csv')
reputation_wide <- reputation |>
  select(-rank) |>
  pivot_wider(names_from = name,
              values_from = score)
reputation_wide <- janitor::clean_names(reputation_wide)
```

```{r}
write_csv(reputation, "reputation.csv")
write_csv(reputation_wide, "reputation_wide.csv")
```















```{r}
plastics_data <- readr::read_csv("plastics.csv")
```

```{r}
str(plastics_data, give.attr = FALSE)
```

```{r}
plastics_data |>
  summarize(mean = mean(hdpe, na.rm = TRUE),
            median = median(hdpe, na.rm = TRUE),
            sd = sd(hdpe, na.rm = TRUE))
```

```{r}
plastics_data |>
  filter(!is.na(hdpe)) |>
  ggplot(aes(x = hdpe)) +
  geom_histogram()
```

```{r}
plastics_data |>
  filter(hdpe > 0) |>
  ggplot(aes(x = hdpe)) +
  geom_histogram()
```

```{r}
plastics_data |>
  summarize(mean = mean(ldpe, na.rm = TRUE),
            median = median(ldpe, na.rm = TRUE),
            sd = sd(ldpe, na.rm = TRUE))
```

```{r}
plastics_data |>
  filter(!is.na(ldpe)) |>
  ggplot(aes(x = ldpe)) +
  geom_histogram()
```

```{r}
plastics_data |>
  filter(ldpe > 0) |>
  ggplot(aes(x = ldpe)) +
  geom_histogram()
```

```{r}
skimr::skim(plastics_data)
```

```{r}
plastics_data |>
  filter(!is.na(hdpe)) |>
  filter(!is.na(ldpe)) |>
  ggplot(aes(x = ldpe, y = hdpe)) +
  geom_point()
```

```{r}
correlation_value <- plastics_data |>
  summarize(r = cor(hdpe, ldpe,
                    use = "pairwise.complete.obs")) |>
  unlist()
```

```{r}
plastics_data |>
  filter(!is.na(hdpe)) |>
  filter(!is.na(ldpe)) |>
  ggplot(aes(x = ldpe, y = hdpe)) +
  geom_point() +
  labs(title = "Plastic Pollution",
       subtitle = paste0("correlation: r = ", 
                         round(correlation_value, 4)),
       caption = "Source: Break Free from Plastic",
       x = "low density polyethylene count",
       y = "high density polyethylene count")
```

```{r}
plastics_numeric_data <- plastics_data |>
  select(where(is.numeric)) |>
  select(-year)
```

```{r}
corrplot(cor(plastics_numeric_data,
             use = "pairwise.complete.obs"),
         method = "number")
```

```{r}
corrplot(cor(plastics_numeric_data,
             use = "pairwise.complete.obs"),
         method = "color",
         order = "alphabet")
```

```{r}
corrplot(cor(plastics_numeric_data,
             use = "pairwise.complete.obs"),
         addCoef.col = "black",
         order = "alphabet")
```

```{r}
plastics_data |>
  ggplot(aes(x = parent_company, y = grand_total)) +
  geom_bar(stat = "identity")
```

```{r}
plastics_data |>
  group_by(parent_company) |>
  mutate(company_count = sum(grand_total)) |>
  ungroup() |>
  select(parent_company, company_count) |>
  distinct() |>
  top_n(10) |>
  ggplot(aes(x = parent_company, y = company_count)) +
  geom_bar(stat = "identity")
```


```{r}
plastics_data |>
  filter(!is.na(parent_company)) |>
  filter(!(parent_company %in%
             c("Grand Total", "null", "NULL", "Assorted", "Unbranded"))) |>
  group_by(parent_company) |>
  mutate(company_count = sum(grand_total)) |>
  ungroup() |>
  select(parent_company, company_count) |>
  distinct() |>
  top_n(10) |>
#   mutate(parent_company = replace(parent_company,
#                                  parent_company == "Tamil Nadu Co-operative Milk Producers' Federation Ltd
# ",
# "Tamil Nadu Co-op")) |>
  mutate(company_ranked = fct_reorder(parent_company, company_count)) |>
  ggplot(aes(x = company_ranked, y = company_count,
             fill = company_ranked)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Plastic Pollution",
       subtitle = "Top 10 sources for plastic pollution",
       caption = "Source: Break Free from Plastic",
       x = "parent company",
       y = "total count of recovered plastics") +
  theme(legend.position = "none")
```